config/routes.rb
Rails.application.routes.draw do

 root 'storages#index'

 resources :storages do
   resources :items
 end
  
 resources :users

  match '/signup',  to: 'users#new',            via: 'get'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :storage
end

app/models/storage.rb
# -*- coding: utf-8 -*-
class Storage < ActiveRecord::Base
    has_many :items
    validates :title, 
    presence: { message: "入力してください"},
        length: {maximum: 20, message: "長すぎ"}
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @storage = Storage.find(params[:storage_id])
        @task = @storage.items.create(item_params)
        redirect_to storage_path(@storage.id)
  end

  private

    def item_params
        params[:item].permit(:title)
    end


end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController

  def index
    @storages = Storage.all
  end
  
  def show
    @storage = Storage.find(params[:id])
  end
  
  def new
    @storage = Storage.new
  end
  
  def create
    @storage = Storage.new(storage_params)
    if @storage.save
      redirect_to storages_path
    else
      render 'new'
    end
  end

  def edit
    @storage = Storage.find(params[:id])
  end

  def update
    @storage = Storage.find(params[:id])
        if @storage.update(storage_params)
           redirect_to storages_path
        else
           render 'edit'
        end
  end

  def destroy
    @storage = Storage.find(params[:id])
        @storage.destroy
        redirect_to storages_path
  end

  private

    def storage_params
        params[:storage].permit(:title, :url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                              :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 与えられたユーザーのGravatar (http://gravatar.com/) を返す。
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cloreco" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Cloreco</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
                      <li><%= link_to "フォローする", "/path2"  %></li>
                      <li><%= link_to "ログイン",  signup_path  %></li>
                    </ul>
                 </div>
            </div>
         </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>フォローランキング</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/storages/_form.erb
<%= form_for @storage do |f| %>
 
<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <% if @storage.errors.any? %>
    <%= @storage.errors.messages[:title][0] %>
    <% end %>          
</p>

<p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
    <% if @storage.errors.any? %>
    <%= @storage.errors.messages[:title][0] %>
    <% end %>          
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/storages/edit.html.erb
<h1>edit</h1>

<%= render 'form' %>
 

app/views/storages/index.html.erb
<p><%#= link_to "収納", new_storage_path %></p>
<p><%= button_to "収納の追加", new_storage_path, :class => "button", :method => :get  %></p>


<% @storages.each do |storage| %>
  <div class="container">
　　  <div class="col-md-3">
       <img class="img-responsive" src=<%= storage.url %> width="300" height="300" alt="" />
       <p>
       <%= link_to "[編集]", edit_storage_path(storage.id) %>
       <%= link_to "[削除]", storage_path(storage.id),method: :delete,
                         data: {confirm: "are you sure"} %>
       </p>
    </div>
    <div class="col-md-9">
    <p><b>アイテム名  :</b>nike dunk hi<br><b>サイズ :</b>28inch<b><br>カラー :</b>navy<br>
         <b>購入場所  :</b>メルカリ<br><b>購入時期  :</b>2014/11/22<br>
    </p>
    </div>
    <p>
    <%= link_to "[編集]", edit_storage_path(storage.id) %>
    <%= link_to "[削除]", storage_path(storage.id),method: :delete,
                         data: {confirm: "are you sure"} %>
    </p>
  </div>
<% end %>

app/views/storages/new.html.erb
<h1>add new</h1>

<%= form_for @storage do |f| %>
 
<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <% if @storage.errors.any? %>
    <%= @storage.errors.messages[:title][0] %>
    <% end %>          
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/storages/show.html.erb
<h2><%= @storage.title %></h2>

<%= form_for [@storage, @storage.items.build] do |f| %>
<%= f.text_field :title %>
<%= f.submit %>
<% end %>

<ul>
<% @storage.items.each do |item| %>
<li><%= item.title %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up')  %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-xs12 col-sm-6 col-sm-offset-3">
    <%= form_for @user, html: { role: "form"}  do |f| %>
          <%= render 'shared/error_messages' %>
    <div class="form-group">
       <%= f.label :name %>
       <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control"  %>
    </div>

    <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control"  %>
    </div>

    <div class="form-group">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: "form-control"  %>
    </div>

    <%= f.submit "Create my account", class: "btn btn-lg btn-primary" %>

   <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>